#!/bin/bash -e

# Usage: /sbin/zammad-backup
backupPath="/data/backup"
backupFileSuffix="-zammad.tar.gz"
backupDbSuffix="-zammad-db.tar.gz"
databaseFile="database.sql"

source /container/run/environment.sh

# delete backups that are over $ZAMMAD_BACKUP_TTL days
find $backupPath -type f -mtime +$ZAMMAD_BACKUP_TTL -exec rm {} \;

# date format for the dump file name
dateFileFormat="+%Y%m%dT%H%M%S"
backupFilePath="$backupPath/$(date "$dateFileFormat")$backupFileSuffix"

# save config and plugins except default ones
tar -czf $backupFilePath -C / ${ZAMMAD_DIR:1}
chmod 600 $backupFilePath

# backup database
. /container/service/backup/assets/tool/zammad-get-db-params
rm -rf $databaseFile || true

mysqldump -u $databaseUser -p$databasePassword --host $host $database > $databaseFile

backupFilePath="$backupPath/$(date "$dateFileFormat")$backupDbSuffix"
tar -czf $backupFilePath $databaseFile
chmod 600 $backupFilePath

rm -rf $databaseFile

exit 0
